name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/checkout@v3
#       - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.APPLICATION_DEV }}" > ./src/main/resources/application.properties
      - run: cat ./src/main/resources/application.properties
      #        gradle properties
#      - run: touch ./gradle/wrapper/gradle-wrapper.properties
#      - run: echo "${{ secrets.GRADLE }}" > ./gradle/wrapper/gradle-wrapper.properties
#      - run: cat ./gradle/wrapper/gradle-wrapper.properties

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew


      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
